### ISSUE TITLE
附图指标和主图k线图缩放不统一。

### ISSUE THREAD

**Issue by 591958857** [No-Trade-No-Life/Yuan#114]
### Describe the bug

缩小主图，附图指标会变成最大；缩小附图，主图显示会变成最大。
附图指标的时间显示不正确。
![企业微信截图_16940746616105](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/05200c67-c0d1-4b00-aa08-bd83a5f22e55)

### To Reproduce

显示附图指标即可重现。

**Comment by zccz14** [comment]
@591958857 
可能与 #112 引入的bug有关，现在还能复现吗？

**Comment by 591958857** [comment]
试了一下，这个问题应该解决了
