### ISSUE TITLE
主图指标显示在k线的最左边

### ISSUE THREAD

**Issue by 591958857** [No-Trade-No-Life/Yuan#115]
### Describe the bug

![image](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/4f0304d0-9df9-4449-be20-e6664ae0f601)

### To Reproduce

运行有主图指标的策略即可。

**Comment by zccz14** [comment]
应该已经解决了。
#112 这个 commit 引入的，后来 revert 了，现在重新测试过 #117
