### ISSUE TITLE
如何计算连个序列的差值序列

### ISSUE THREAD

**Issue by nanfeng-dada** [No-Trade-No-Life/Yuan#118]
已通过如下方式获取到high和low序列，如何计算high-low的差值序列
`const { product_id, open, high, low, close } = useParamOHLC("SomeKey");`

**Comment by mage1028** [comment]
@zccz14

**Comment by zccz14** [comment]
使用一个序列映射即可创造你需要的序列

useSeriesMap(“some name”, high, {}, i => high[i]-low[i])
