### ISSUE TITLE
能否提供一个盘中交易策略模型案例

### ISSUE THREAD

**Issue by nanfeng-dada** [No-Trade-No-Life/Yuan#119]
案例中提供的模型都是当前K线结束后交易（close.length-1）,如下，
```
// NOTE: 使用当前 K 线的上一根 K 线的收盘价，保证策略在 K 线结束时才会执行
  const idx = close.length - 2;
  // 设置仓位管理器
  const pL = useSinglePosition(product_id, PositionVariant.LONG);
  const pS = useSinglePosition(product_id, PositionVariant.SHORT);

  useEffect(() => {
    if (idx < N) return; // 略过一开始不成熟的均线数据

    if (close[idx] > Upper[idx]) {
      pL.setTargetVolume(1);
      pS.setTargetVolume(0);
    }
    if (close[idx] < Lower[idx]) {
      pL.setTargetVolume(0);
      pS.setTargetVolume(1);
    }
  }, [idx]);
```

能否提供一个盘中交易的模型案例

**Comment by zccz14** [comment]
首先，模型代码的**执行时机**是 K线的开始和结束时，每个K线都会请求模型执行2次。

这是因为，只有K线数据无法提供盘中的信息量。

1. 如果使用插值法，会使得回测和实盘产生差距，因此不推荐使用插值法来增加额外的执行时机。

2. 如果使用更小周期，更细粒度的行情数据作为补充，这个是没问题的，可以参考示例中的 R-Breaker 策略（日内回转）。
R-Breaker 可以看作日线的盘中策略。

3. 如果你只是希望获取最新这个可能没有收盘的K线的数据，使用 close.length - 1 作为下标访问即可。

4. 如果你希望提前预埋单，请使用 `useExchange()`  搭配 `submitOrder`, `modifyOrder`, `cancelOrder` API，发送 type 为 `OrderType.LIMIT` 和 `OrderType.STOP` 的订单，即可完成预埋单的模拟，后续我们会开放一个网格交易策略作为示例。

**Comment by zccz14** [comment]
在示例项目中里添加了一个网格交易策略：

https://github.com/No-Trade-No-Life/Yuan-Public-Workspace/blob/main/%40models/grid.ts

你也可以直接通过【导入示例项目】来获得，路径是 `/@models/grid.ts`
