### ISSUE TITLE
代码写的是开多仓，实际回测却是开空仓

### ISSUE THREAD

**Issue by 591958857** [No-Trade-No-Life/Yuan#124]
### Describe the bug

![image](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/1222a3db-f2bc-4e8d-8e12-80390f8ed987)
![image](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/a93d5893-c38b-446a-b1f8-8faca7066bed)
![image](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/2eed64f9-db2a-4a90-8e5a-8751e1fceb6f)
![image](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/c4aeca5b-cac7-4a3d-bad1-60de63bb9e42)
代码里面写的是开多仓，但是实际回测时显示的都是开空仓。

### To Reproduce

回测策略即可

**Comment by zccz14** [comment]
检查一下是否开启了（对手盘）的参数
开启的情况会反向开单
