### ISSUE TITLE
migrate packages to Yuan public repo

### ISSUE THREAD

**Issue by zccz14** [No-Trade-No-Life/Yuan#44]

**Comment by Thrimbda** [comment]
Packages to migrate:

Libraries:
- [X] kernel
- [X] agent
- [X] protocol

Tools:
- [X] dependency-hash
- [X] docker-bake #42 

Apps:
- [X] agent
- [X] email-notifier
- [X] feishu-notifier
- [X] host
- [X] market-data-collector
- [X] metrics-collector
- [X] mongodb-storage
- [X] trade-copier
- [x] workbench

**Comment by Thrimbda** [comment]
all set!
praise the mighty zccz14
