### ISSUE TITLE
bug: 策略连续跑两次以上，走势图中的开平仓标识会消失。

### ISSUE THREAD

**Issue by 591958857** [No-Trade-No-Life/Yuan#84]
### Describe the bug

![1693644656251](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/94f86691-d4d1-4759-8620-be7e82e18e8d)

### To Reproduce

策略连续跑两次以上即可出现。

**Comment by zccz14** [comment]
@591958857  临时方案：点击左上角的刷新按钮。

**Comment by zccz14** [comment]
意外地在 #196  和 #200 中顺便修复了。
