### ISSUE TITLE
bug: 实际开仓价与对应的K线的开盘价不一致。

### ISSUE THREAD

**Issue by 591958857** [No-Trade-No-Life/Yuan#86]
### Describe the bug

![1693645200058](https://github.com/No-Trade-No-Life/Yuan/assets/5301653/82707574-fafa-4425-966f-9838c28cb7c7)

### To Reproduce

部分位置是准确的，部分位置有问题。

**Comment by zccz14** [comment]
@591958857 
这个是因为公共品种库中默认加入了 2跳的点差。买入时价格会偏高 2跳。属于正常现象。
如果不符合预期，可以继续讨论一下
